### ISSUE TITLE
Can not serve

### ISSUE THREAD

**Issue by chraibi** [aksakalli/jekyll-doc-theme#3]
Following the instructions in the readme I still get the following errors

```
➔ jekyll serve
WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.4, ~> 0.9)
      rb-inotify (>= 0.9.7, ~> 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:317:in `check_for_activated_spec!': You have alreadyactivated sass 3.4.24, but your Gemfile requires sass 3.4.23. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:32:in `block in setup'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:27:in `map'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:27:in `setup'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler.rb:101:in `setup'
        from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.5.0/lib/jekyll/plugin_manager.rb:48:in `require_from_bundler'
        from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.5.0/exe/jekyll:9:in `<top (required)>'
        from /usr/local/bin/jekyll:23:in `load'
        from /usr/local/bin/jekyll:23:in `<main>'
```

I don't think it is a good idea to start editing all the versions (I did it for fun, but...)

Any idea what is going on?

**Comment by aksakalli** [comment]
Hey,

my bad, instead you need to run it like `bundle exec jekyll serve` 

see [stackoverflow](https://stackoverflow.com/questions/6317980/you-have-already-activated-x-but-your-gemfile-requires-y), [jekyll docs](https://jekyllrb.com/docs/quickstart/)

I am also updating the `README.md`, thank you for your feedback.

**Comment by chraibi** [comment]
Sweet! Thanks!
